# Generated by Django 3.2.5 on 2021-11-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='experience_level',
            field=models.IntegerField(blank=True, choices=[(6, 'Novice'), (5, 'Beginner'), (4, 'Intermediate'), (3, 'Intermediate2'), (2, 'Advanced'), (1, 'Expert')], null=True),
        ),
    ]
