# Generated by Django 3.2.5 on 2021-11-16 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_member_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='experience_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
