# Generated by Django 3.2.5 on 2021-12-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('clubs', '0002_member_officer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.DeleteModel(
            name='owner',
        ),
    ]
