# Generated by Django 3.2.5 on 2021-11-16 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211116_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='experience_level',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
