# Generated by Django 3.2.5 on 2021-12-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Novice'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Applicant'), (2, 'Member'), (3, 'Officer'), (4, 'Owner')]),
        ),
    ]
