# Generated by Django 3.2.5 on 2021-12-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=True),
        ),
    ]
