# Generated by Django 3.2.5 on 2021-12-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USERTYPE',
        ),
    ]
