# Generated by Django 3.2.5 on 2021-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_delete_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Member', 'Member'), ('Officer', 'Officer'), ('Owner', 'Owner')], default='Member', max_length=255),
        ),
    ]
