# Generated by Django 3.2.5 on 2021-12-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_user_is_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
