# Generated by Django 3.2.5 on 2021-12-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
